import Container from "@/components/Container";
import "./globals.css";
import Header from "@/components/layouts/Header";

export const metadata = {
  title: "Cyber Punk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased h-full relative`}>
        <Container className="container h-full absolute bg-transparent left-1/2 top-0 -translate-x-1/2 line_left line_right -z-1"></Container>
        <Header />
        {children}
      </body>
    </html>
  );
}
